// ================================================================
//  ✏️  CONTENT.JS — EDIT ALL YOUR TEXT RIGHT HERE
//
//  This is the only file you need to touch.
//  Change any text between the quotes " ".
//  Don't delete commas or brackets — just swap the words.
// ================================================================


// ── SITE NAME (shows in the nav bar) ────────────────────────────
export const siteConfig = {
  siteName: "Climate Change",        // ← your project name
}


// ── NAV BAR LINKS ───────────────────────────────────────────────
// These are the clickable labels in the top navigation.
// They scroll to each section automatically.
export const navLabels = {
  section1:   "The Issue",       // ← rename these however you like
  section2:   "Take Action",
  section3:   "Solutions",
  calculator: "Quiz",
  citations:  "Sources",
}


// ── HERO (the very first thing people see) ───────────────────────
export const hero = {
  badge:          "Research/Project By: Vrishin,Jordan,Alex,Jaxson,Steeven",   // ← small label above the headline
  headline:       "Stop Climate Change", // ← main bold title (first line)
  headlineAccent: "Learn From This Website!",       // ← second line (shown in muted color)
  subheadline:    "Climate Change is a global crisis that requires urgent action. This project explores the causes, impacts, and solutions to this dangerous issue.",  // ← smaller text below the headline
  ctaPrimary:     "Learn More",              // ← first button label
  ctaSecondary:   "Take the Quiz",           // ← second button label

  // Stats displayed in the row of boxes below the buttons.
  // Change the value and label, or add/remove boxes.
  stats: [
    { value: "1,000,000", label: "The amount of species at risk that is caused by climate change" },
    { value: "250,000", label: "The amount of deaths that Climate Change has caused" },
    { value: "10%", label: "The percentage of the population affected by climate change" },
    { value: "50%", label: "The percentage of greenhouse gas emissions from transportation" },
  ],
}


// ── SECTION 1: THE ISSUE ────────────────────────────────────────
// Cards that explain the problem/topic.
// Each card has a title, subtitle, body paragraph, and a stat.
export const issueSection = {
  badge:          "THE ISSUE",
  headline:       "Some of the threats of climate change",
  headlineAccent: "read below to learn more.",
  subheadline:    "This Section explains some of the major issue of Climate Change. Each card focuses on a different aspect of the problem.",

  // Add or remove cards. Each one needs all 5 fields.
  cards: [
    {
      title:     "Rising Global Temperatures",
      subtitle:  "Tracking the Thermal Trend",
      body:      "Average global temperatures have climbed significantly(approximately 1.4 degrees Fahrenheit), driven primarily by human greenhouse gas emissions since the Industrial Revolution. This warming has messed up the weather patterns which cause more heatwaves. droughts, adn wildfires which harms our planet along with the species that live on it.",
      stat:      "+1.2°C",          // ← big bold number shown at the bottom of the card
      statLabel: "Increase in global tempratures the industrial revolution",  // ← small text shown below the stat
    },
    {
      title:     "The Ocean Warming up",
      subtitle:  "Lots of Heat trapped in the Ocean",
      body:      "The ocean caputres 90% of the excess heat that is generated by the emissions of greenhouse gases. This has caused the ocean to warm up which has led to coral bleaching, rising sea levels, and disrupted marine ecosystems.",
      stat:      "90%",
      statLabel: "of excess global warming heat abosorbed by oceans",
    },
    {
      title:     "Ice Loss",
      subtitle:  "Melting Polar Reservoirs",
      body:      "Rising tempratures are causing polar ice shjeets and glaciers to melt at an alarming rate. This causes sea levels to rise which can be a threat to habitats.",
      stat:      "427B",
      statLabel: "metric tons of polar ice lost per year",
    },
    {
      title:     "Coastal Flooding Risks",
      subtitle:  "Communities on the Edge",
      body:      "As sea levels rise, ocean water pushes further inland during high tides and storms. This causes regular flooding that damages homes, roads, and other important buildings. It also washes away beaches and puts millions of people who live near the coast in danger.",
      stat:      "300M",
      statLabel: "people vulnerable to coastal flooding globally",
    },
    {
      title:     "Extreme Weather Intensity",
      subtitle:  "The Price of an Energized Atmosphere",
      body:      "A hotter atmosphere has more water and energy in it, which causes stronger storms, wildfires, and droughts. These severe weather events hurt local businesses, make it hard for emergency workers to respond, and force people to leave their homes and communities.",
      stat:      "$150B+",
      statLabel: "in annual economic damages from climate disasters",
    },
    {
      title:     "Renewable Energy Transition",
      subtitle:  "Engineering the Civic Shift",
      body:      "Using clean energy like wind and solar instead of coal and oil is the best way to stop climate change. Wind and solar power are now much cheaper, so it makes sense to switch to them to protect our planet.",
      stat:      "80%",
      statLabel: "drop in solar energy costs over the last decade",
    },
  ],
}


// ── SECTION 2: TAKE ACTION ──────────────────────────────────────
// A checklist of things people can do. Grouped into categories.
// Each action has:
//   text   – the action itself
//   impact – shown in small colored text below it
//   easy   – set to true to show an "Easy win" badge, false to hide it
export const actionSection = {
  badge:          "TAKE ACTION",
  headline:       "Things people can do",
  headlineAccent: "to make a difference",
  subheadline:    "Click the checkboxes to track which actions you're committing to.",

  callout: {
    line1: "",
    stat:  "YOU CAN MAKE A DIFFERENCE!",  // ← big bold stat shown in the colored box
    line2: "",
  },

  // Each category expands when clicked. Add as many as you need.
  categories: [
    {
      title: "Action At Home",
      actions: [
        { text: "Switch to LED lighting", impact: "", easy: false  },
        { text: "Reduce food waste", impact: "", easy: false  },
        { text: "Unplug unused electronics", impact: "", easy: false },
        { text: "Adjust your thermostat appropriately", impact: "", easy: false },
      ],
    },
    {
      title: "Action In Your Community",
      actions: [
        { text: "Attend local government meetings", impact: "", easy: false  },
        { text: "Use green transit(Walk,Bike,Public Transport)", impact: "", easy: false  },
        { text: "Support climate-friendly policies", impact: "", easy: false },
        { text: "Participate in community clean-up events", impact: "", easy: false },
      ],
    },
    {
      title: "Action To Make a Difference",
      actions: [
        { text: "Advocate for climate action", impact: "", easy: false  },
        { text: "Join or support environmental organizations", impact: "", easy: false },
        { text: "Participate in climate marches or rallies", impact: "", easy: false },
      ],
    },
  ],
}


// ── SECTION 3: SOLUTIONS ────────────────────────────────────────
// Cards showcasing solutions, programs, or key facts.
// Each card also shows a "savings" or impact number.
export const solutionsSection = {
  badge:          "SOLUTIONS",
  headline:       "Ways to make a real difference",
  headlineAccent: "and why they work.",
  subheadline:    "Solutions that can make an impact",

  // A highlighted banner at the top of this section (optional).
  banner: {
    emoji:    "💡",
    title:    "The Inflation Reduction Act — Driving Clean Energy Laws",
    body:     "This landmark civic program represents the largest investment in climate and energy in U.S. history. It provides massive funding and tax incentives to rapidly transition communities to clean energy while cutting household utility bills.",
    ctaLabel: "",
    ctaUrl:   "",   // ← replace with a real link or remove
  },

  // Solution cards. Add or remove as needed.
  solutions: [
    {
      title:       "Grid Modernization",
      subtitle:    "Transitioning to 100% clean electricity",
      description: "Replacing fossil-fuel power plants with utility-scale wind, solar, and geothermal energy is the most impactful way to stop greenhouse gas emissions. Upgrading our national electrical grid ensures this clean power can be distributed reliably to every home and business.",
      impact:      "0 Tons",
      impactNote:  "of carbon emitted by fully reneable energy grids",
      tag:         "Most Effective",   // ← small label in the top corner
      features: [
        "Drastically reduces carbon dioxide emissions from power generation.",
        "Creates millions of long-term jobs in engineering and construction.",
        "Utilizes naturally endless energy resources like sunlight and wind.",
        "Improves community air quality by shutting down coal and gas plants.",
        "Builds a stronger grid less prone to blackouts during heatwaves.",
      ],
    },
    {
      title:       "Energy Efficiency Upscaling",
      subtitle:    "Maximizing the power we already use",
      description: "Remodeling existing homes, schools, and commercial buildings with smart tech drastically reduces our overall energy demand. Utilizing high-efficiency heat pumps, modern insulation, and smart appliances makes conservation simple and immediate.",
      impact:      "Up to 50%",
      impactNote:  "less heating and cooling energy used by modern heat pumps",
      tag:         "Widely Available",
      features: [
        "Lowers monthly heating and cooling costs for families.",
        "Can be easily installed in existing buildings without rebuilding.",
        "Takes immense pressure off local electrical grids during peak hours.",
        "Qualifies homeowners for helpful government tax rebates.",
      ],
    },
    {
      title:       "Urban Green Space Expansion",
      subtitle:    "Harnessing nature within our cities",
      description: "Planting urban forests, constructing green roofs, and expanding community parks helps combat the environmental strain on cities. These natural solutions absorb excess rainwater to prevent flooding while cooling down paved neighborhood surfaces.",
      impact:      "Up to 10°F",
      impactNote:  "cooler temperatures in shaded urban park areas",
      tag:         "Community-Based",
      features: [
        "Trees naturally pull carbon dioxide directly out of the air.",
        "Reduces dangerous urban heat island effects in concrete areas.",
        "Absorbs heavy rainfall to protect city storm drains from overflowing.",
      ],
    },
    {
      title:       "Clean Transit Infrastructure",
      subtitle:    "Revolutionizing how communities move",
      description: "Transitioning public transit fleets, school buses, and municipal vehicles to zero-emission electric alternatives dramatically cuts urban air pollution. Expanding electric vehicle (EV) fast-charging networks ensures clean transportation is accessible to everyone in the community.",
      impact:      "Zero",
      impactNote:  "tailpipe emissions produced by electric transit vehicles",
      tag:         "Future-Focused",
      features: [
        "Eliminates harmful tailpipe emissions from daily city traffic.",
        "Lowers long-term maintenance costs for public school districts.",
        "Reduces reliance on petroleum and volatile fossil fuel markets.",
        "Provides quiet, exhaust-free transit options for urban residents.",
        "Creates a reliable charging network for private EV drivers.",
      ],
    },
  ],
}


// ── CALCULATOR / QUIZ ───────────────────────────────────────────
// An interactive quiz. Each question has options.
// The score at the end is based on "points" — higher = better.
// Customize questions and options for your topic.
export const quizSection = {
  badge:          "QUIZ",
  headline:       "Test your knowledge",
  headlineAccent: "on Climate Change.",
  subheadline:    "(Hope you payed attention)",

  results: {
    title:    "Your Results",
    subtitle: "Here's what your answers say:",
    ctaReset: "Try Again",
    ctaAction:"Learn what you can do →",
    levels: [
      // These messages show based on score. Customize each one.
      { minScore: 0,  maxScore: 2,  label: "Just Getting Started",  message: "No worries — that's why projects like this exist! Read through the sections above to learn more." },
      { minScore: 3,  maxScore: 5,  label: "Getting There",         message: "Good awareness! You know the basics — now it's time to go deeper and take action." },
      { minScore: 6,  maxScore: 8,  label: "Well Informed",         message: "Great knowledge! You're clearly paying attention. Share what you know with others." },
      { minScore: 9,  maxScore: 10, label: "Expert Level",          message: "Outstanding! You're deeply informed. Consider getting involved in advocacy or leadership." },
    ],
  },

  // Each question needs a "label" and 4 options.
  // Set the correct option's points to 2, a partially-right one to 1, wrong to 0.
  questions: [
    {
      id:    "q1",
      label: "Question 1: how many species are at risk of extinction due to climate change?",
      options: [
        { label: "2,000,000", value: "a", points: 0 },
        { label: "1,000,000", value: "b", points: 2 },  // ← correct answer
        { label: "3,000,000", value: "c", points: 0 },
        { label: "10,000,000", value: "d", points: 0 },
      ],
    },
    {
      id:    "q2",
      label: "Question 2:How many people are vulnerable to coastal flooding globally?",
      options: [
        { label: "300M", value: "a", points: 2 },
        { label: "1B", value: "b", points: 0 },
        { label: "250M", value: "c", points: 0 },
        { label: "10M", value: "d", points: 0 },
      ],
    },
    {
      id:    "q3",
      label: "Question 3: How much percent has solar energy costs dropped over the last decade?",
      options: [
        { label: "50%", value: "a", points: 0 },
        { label: "70%", value: "b", points: 0 },
        { label: "90%", value: "c", points: 0 },
        { label: "80%", value: "d", points: 2 },
      ],
    },
    {
      id:    "q4",
      label: "Question 4: which one of these are solutions to help stop climate change?",
      options: [
        { label: "switching to renewable energy", value: "a", points: 0 },
        { label: "improving energy efficiency", value: "b", points: 0 },
        { label: "using electric vehicles and smart thermostats", value: "c", points: 0 },
        { label: "All of the above", value: "d", points: 2 },
      ],
    },
    {
      id:    "q5",
      label: "Question 5: How many metric tons of polar ice are lost per year?",
      options: [
        { label: "1B", value: "a", points: 0 },
        { label: "200B", value: "b", points: 0 },
        { label: "300B", value: "c", points: 0 },
        { label: "427B", value: "d", points: 2 },
      ],
    },
  ],
}


// ── CITATIONS / SOURCES ─────────────────────────────────────────
// Add one entry per source. All fields are shown on the page.
// The "note" field explains which fact this source supports.
export const citations = {
  badge:          "BIBLIOGRAPHY",
  headline:       "Sources &",
  headlineAccent: "Citations",
  subheadline:    "All facts and statistics in this project come from the sources listed below.",
  projectNote:    "All Citations In MLA Format are in the google slides presentation. This is just a foramlity.",

  // Each source entry:
  sources: [
    {
      number: 1,
      author: "United Nations",
      title:  "Actions for a Healthy Planet",
      source: "The United Nations",
      year:   "2026",
      url:    "https://www.un.org/en/actnow/ten-actions",   // ← paste the real link here
      note:   "",
    },
    {
      number: 2,
      author: "United States Environmental Protection Agency",
      title:  "Clean School Bus Program",
      source: "US EPA",
      year:   "2026",
      url:    "https://www.epa.gov/cleanschoolbus",
      note:   "",
    },
    {
      number: 3,
      author: "NASA",
      title:  "Global Climate Change: Vital Signs of the Planet",
      source: "NASA's Jet Propulsion Laboratory",
      year:   "2026",
      url:    "https://climate.nasa.gov/",
      note:   "",
    },
    {
      number: 4,
      author: "United States Environmental Protection Agency",
      title:  "Heat Island Effect: Benefits of Trees and Vegetation",
      source: "US EPA",
      year:   "2026",
      url:    "https://www.epa.gov/heatislands/using-trees-and-vegetation-reduce-heat-islands",
      note:   "",
    },
    {
      number: 5,
      author: "United States Department of Energy",
      title:  "Inflation Reduction Act of 2022",
      source: "Department of Energy",
      year:   "2026",
      url:    "https://www.energy.gov/lpo/inflation-reduction-act-2022",
      note:   "",
    },
  ],
}


// ── FOOTER ──────────────────────────────────────────────────────
export const footer = {
  description: "Website made by Vrishin Venkatesh",  // ← your name(s) or group name
  copyright:   "© 2026 Civics Climate Change Project | Created by Vrishin,Jordan,Alex,Jaxson,Steeven",  // ← your name(s) or group name
}
